version: '3'

services:
  app:
    build: .
    entrypoint: ./entrypoint.sh
    command: serve
    environment:
      NODE_ENV: development
    volumes:
      - ./src:/app
    ports:
      - "1337:1337"
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
    - "5432:5432"
    environment:
      - DB_USER=developer
      - DB_PASS=developer
      - DB_NAME=db_test,db_dev
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
