postgres:
  image: sameersbn/postgresql
  ports:
  - "5432:5432"
  environment:
    - DB_USER=developer
    - DB_PASS=developer
    - DB_NAME=db_test,db_dev
  volumes:
    - ./data/postgres:/var/lib/postgresql/data
swagger:
  image: swaggerapi/swagger-ui
  # volumes:
  #     - ./test-swagger.json /Users/oliviervandenmooter/project/v2/nodejs-template-to-go/swagger/swagger.yml
  ports:
    - "80:8080"
